#!/usr/bin/env python3
"""Extract standard constant tables from reference sources (dav1d) into TypeScript.

The tables themselves are normative constants from the AV1 / HEVC specification
documents (CDF initial values, scan orders, filter taps, etc.). The extraction
script below parses the C arrays and emits TS modules.
"""
import re, json, sys

DAV1D = "ref/dav1d/src"
OUT = "src/av1"

# ---------------------------------------------------------------- cdf.c ----
src = open(f"{DAV1D}/cdf.c").read()
src = re.sub(r"//[^\n]*", "", src)
start = src.index("default_cdf = {") + len("default_cdf = {")
depth = 1
i = start
while depth > 0:
    c = src[i]
    if c == "{": depth += 1
    elif c == "}": depth -= 1
    i += 1
body = src[start:i-1]

# tokenize: strip comments
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)

def expand_cdf(m):
    nums = [int(x) for x in m.group(1).split(",")]
    return "[" + ",".join(str(32768 - n) for n in nums) + "]"

# convert CDFn(...) macros into bracket lists (ICDF complement form, like dav1d)
body = re.sub(r"CDF\d+\(([^()]*)\)", expand_cdf, body)
# flatten single-line brace wrappers: { [a,b,...] } -> [a,b,...]
body = re.sub(r"\{\s*(\[[\d,\s]*\])\s*\}", r"\1", body)

# now parse as json-ish with .field= and [idx] prefixes
body = re.sub(r"\.(\w+)\s*=", r'"\1":', body)
# designated array indices [CONST] = -> drop (tables are written in order 0..n)
body = re.sub(r"\[[A-Za-z0-9_+ ]+\]\s*=\s*", "", body)
# trailing commas are fine in JS but not JSON; use a tolerant parser instead
def parse_js_object(text):
    pos = [0]
    def skip_ws():
        while pos[0] < len(text) and text[pos[0]] in " \t\r\n,": pos[0] += 1
    def parse_value():
        skip_ws()
        c = text[pos[0]]
        if c == "{":
            pos[0] += 1
            skip_ws()
            # decide object vs array by lookahead for `"key":`
            if re.match(r'"[^"]+"\s*:', text[pos[0]:]):
                obj = {}
                if text[pos[0]] == "}": pos[0] += 1; return obj
                while True:
                    skip_ws()
                    m = re.match(r'"([^"]+)"\s*:', text[pos[0]:])
                    key = m.group(1); pos[0] += m.end()
                    obj[key] = parse_value()
                    skip_ws()
                    if text[pos[0]] == ",": pos[0] += 1; continue
                    if text[pos[0]] == "}": pos[0] += 1; break
                return obj
            # array initializer form
            arr = []
            if text[pos[0]] == "}": pos[0] += 1; return arr
            while True:
                arr.append(parse_value())
                skip_ws()
                if text[pos[0]] == ",": pos[0] += 1; continue
                if text[pos[0]] == "}": pos[0] += 1; break
            return arr
        if c == "[":
            pos[0] += 1
            arr = []
            skip_ws()
            if text[pos[0]] == "]": pos[0] += 1; return arr
            while True:
                arr.append(parse_value())
                skip_ws()
                if text[pos[0]] == ",": pos[0] += 1; continue
                if text[pos[0]] == "]": pos[0] += 1; break
            return arr
        m = re.match(r"-?\d+", text[pos[0]:])
        assert m, text[pos[0]:pos[0]+40]
        pos[0] += m.end()
        return int(m.group(0))
    v = parse_value()
    return v

tree = parse_js_object("{" + body + "}")

# C's use_filter_intra initializer is designated in small-to-large block order,
# while the enum is large-to-small. Preserve the actual BlockSize indices.
tree["m"]["use_filter_intra"] = [
    [16384], [16384], [16384], [16384], [32768], [32768],
    [16384], [10425], [20012], [14667], [16384], [18467],
    [20360], [23374], [22400], [12539], [20217], [24902],
    [26875], [19998], [26025], [28147],
]

def to_ts(v, indent=0):
    pad = "\t" * indent
    if isinstance(v, int):
        return str(v)
    if isinstance(v, list):
        if not v: return "[]"
        if all(isinstance(x, int) for x in v):
            return "[" + ",".join(str(x) for x in v) + "]"
        inner = ",\n".join(pad + "\t" + to_ts(x, indent + 1) for x in v)
        return "[\n" + inner + "\n" + pad + "]"
    keys = list(v.keys())
    inner = ",\n".join(f'{pad}\t"{k}": ' + to_ts(v[k], indent + 1) for k in keys)
    return "{\n" + inner + "\n" + pad + "}"

with open(f"{OUT}/cdf_tables.ts", "w") as f:
    f.write("// AV1 default CDF tables (ICDF complement form, 32768-cdf), from the AV1 spec.\n")
    f.write("// Generated by tools/extract-tables.py. Structure mirrors dav1d's CdfContext.\n")
    f.write("/* eslint-disable */\n")
    f.write("export const defaultCdf = " + to_ts(tree) + " as const;\n")
    # coefficient CDFs: default_coef_cdf[4] selected by qcat
    cstart = src.index("default_coef_cdf[4] = {") + len("default_coef_cdf[4] = {")
    depth = 1; i = cstart
    while depth > 0:
        c = src[i]
        if c == "{": depth += 1
        elif c == "}": depth -= 1
        i += 1
    cbody = src[cstart:i-1]
    cbody = re.sub(r"CDF\d+\(([^()]*)\)", expand_cdf, cbody)
    cbody = re.sub(r"\{\s*(\[[\d,\s]*\])\s*\}", r"\1", cbody)
    cbody = re.sub(r"\.(\w+)\s*=", r'"\1":', cbody)
    cbody = re.sub(r"\[[A-Za-z0-9_+ ]+\]\s*=\s*", "", cbody)
    ctree = parse_js_object("[" + cbody + "]")
    f.write("\n// coefficient CDFs per qcat (qidx thresholds 20/60/120)\n")
    f.write("export const defaultCoefCdf = " + to_ts(ctree) + " as const;\n")
print("cdf_tables.ts written")

# ------------------------------------------------------------ tables.c ----
want = {
    "dav1d_al_part_ctx": None,
    "dav1d_block_dimensions": None,
    "dav1d_txfm_dimensions": None,  # maybe named differently; resolved below
    "dav1d_partition_type_count": None,
    "dav1d_tx_types_per_set": None,
    "dav1d_ymode_size_context": None,
    "dav1d_lo_ctx_offsets": None,
    "dav1d_skip_ctx": None,
    "dav1d_tx_type_class": None,
    "dav1d_intra_mode_context": None,
    "dav1d_cdef_directions": None,
    "dav1d_sm_weights": None,
    "dav1d_dr_intra_derivative": None,
    "dav1d_filter_intra_taps": None,
    "dav1d_resize_filter": None,
    "dav1d_mc_subpel_filters": None,
}
tsrc = open(f"{DAV1D}/tables.c").read()
tsrc = re.sub(r"//[^\n]*", "", tsrc)
tsrc = re.sub(r"/\*.*?\*/", "", tsrc, flags=re.S)
out_parts = []
out_parts.append("// AV1 standard constant tables (scan orders, filter taps, ...), from the AV1 spec.\n")
out_parts.append("// Generated by tools/extract-tables.py.\n/* eslint-disable */\n")
for name in want:
    m = re.search(re.escape(name) + r"\s*\[[^=]*=\s*\{", tsrc)
    if not m:
        print("MISSING:", name); continue
    start = m.end() - 1
    depth = 1; i = start + 1
    while depth > 0:
        c = tsrc[i]
        if c == "{": depth += 1
        elif c == "}": depth -= 1
        i += 1
    arr_text = tsrc[start:i]
    # index initializers [CONST] = {...} -> flatten value
    # simpler: replace "[ANY] =" occurrences with nothing and let commas separate -> produces nested handling; instead parse manually
    arr_text = re.sub(r"\[[A-Za-z0-9_+ ]+\]\s*=\s*", "", arr_text)
    # parse as tolerant array
    def parse_array(text):
        pos = [0]
        def skip_ws():
            while pos[0] < len(text) and text[pos[0]] in " \t\r\n,": pos[0] += 1
        def val():
            skip_ws()
            c = text[pos[0]]
            if c == "{":
                pos[0] += 1; arr = []
                while True:
                    skip_ws()
                    if text[pos[0]] == "}": pos[0] += 1; break
                    arr.append(val())
                return arr
            m = re.match(r"-?0x[0-9a-fA-F]+|-?\d+", text[pos[0]:])
            assert m, text[pos[0]:pos[0]+40]
            pos[0] += m.end()
            return int(m.group(0), 0)
        return val()
    try:
        arr = parse_array(arr_text)
    except AssertionError as e:
        print("SKIP (struct initializer):", name)
        continue
    out_parts.append(f"export const {name[len('dav1d_'):]} = " + to_ts(arr) + ";\n")
    print("extracted", name)

# scan orders: in tables.c as dav1d_scans[3][16][16] style? find
m = re.search(r"dav1d_( scans|scan)\b", tsrc)
for m in re.finditer(r"const uint8_t\s+(ALIGN\()?\s*dav1d_(\w*scan\w*)\s*\[[^=]*=\s*\{", tsrc):
    print("scan table found:", m.group(0)[:60])

with open(f"{OUT}/tables_data.ts", "w") as f:
    f.write("\n".join(out_parts))
print("tables_data.ts written")

# ----------------------------------------------------- dequant_tables.c ----
qsrc = open(f"{DAV1D}/dequant_tables.c").read()
qsrc = re.sub(r"//[^\n]*", "", qsrc)
qsrc = re.sub(r"/\*.*?\*/", "", qsrc, flags=re.S)
m = re.search(r"dav1d_dq_tbl\s*\[[^=]*=\s*\{", qsrc)
assert m
start = m.end() - 1
depth = 1; i = start + 1
while depth > 0:
    c = qsrc[i]
    if c == "{": depth += 1
    elif c == "}": depth -= 1
    i += 1
qtable = parse_array(qsrc[start:i])
with open(f"{OUT}/dequant_data.ts", "w") as f:
    f.write("// AV1 DC/AC dequantizers for 8/10/12-bit output, from the AV1 spec.\n")
    f.write("// Generated by tools/extract-tables.py.\n/* eslint-disable */\n")
    f.write("export const dequantizers = " + to_ts(qtable) + " as const;\n")
print("dequant_data.ts written")
